const CHARS=[
 {id:"glitch",name:"格莉奇",color:"#9e8ce0",line:"今天的故障訊號指向你。"},{id:"catgrass",name:"貓草",color:"#75b78b",line:"慢慢轉，也會走到答案。"},{id:"bambi",name:"斑比",color:"#df91ad",line:"這一格是我的。"},{id:"noah",name:"諾亞",color:"#ce9860",line:"運氣也是可以觀察的。"},{id:"tower",name:"鐵塔",color:"#6c9bc3",line:"轉盤結果已經登記。"},{id:"zerox",name:"0x",color:"#7c8292",line:"……不要再轉一次。"},{id:"blackhole",name:"黑洞先生",color:"#554b62",line:"指針停在星星墜落的地方。"}
];
const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),spinBtn=$("#spin"),statusEl=$("#status"),soundBtn=$("#sound"),exitBtn=$("#exit"),reveal=$("#reveal"),collection=$("#collection"),count=$("#count");
const KEY="glitch-park-wheel:v1",embedded=self!==top,THEME="./assets/audio/glitch-park-theme.mp3";let data={spins:0,owned:[]};try{data={...data,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}let sound=true,audioContext,themeAudio,angle=0,spinning=false,start=0,duration=0,from=0,to=0,w=0,h=0,dpr=1;
if(embedded){const brand=exitBtn.closest(".brand"),topLeft=document.createElement("div"),style=document.createElement("style");topLeft.className="topLeft";brand.before(topLeft);topLeft.append(exitBtn,brand);style.textContent=".topLeft{display:flex;align-items:flex-start;gap:8px}";document.head.append(style)}
const atlas=new Image();atlas.src="./assets/avatar-atlas.webp";atlas.onload=draw;
function avatarStyle(i){return `--x:${i%4/3*100}%;--y:${Math.floor(i/4)*100}%`}
function requestTheme(action,muted=false){if(embedded){parent.postMessage({type:"glitch-park:music",action,track:"theme",url:new URL(THEME,location.href).href,muted},"*");return}themeAudio||=Object.assign(new Audio(THEME),{loop:true,volume:.27});themeAudio.muted=muted;if(action==="play"&&!muted)themeAudio.play().catch(()=>{});if(action==="pause")themeAudio.pause()}
if(embedded){exitBtn.hidden=false;exitBtn.onclick=()=>parent.postMessage({type:"wheel:exit"},"*")}else requestTheme("play");
function beep(freq,dur=.08,vol=.035,type="sine"){if(!sound)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+dur);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+dur)}
soundBtn.onclick=()=>{sound=!sound;soundBtn.textContent=`聲音：${sound?"開":"關"}`;soundBtn.setAttribute("aria-pressed",String(!sound));requestTheme("mute",!sound);if(sound){requestTheme("play");beep(660)}};
function resize(){dpr=Math.min(devicePixelRatio,1.7);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}addEventListener("resize",resize);resize();
function layout(){const tall=h/w>1.18,r=Math.min(w*(tall?.44:.29),h*(tall?.31:.37),310);return{x:w/2,y:h*(tall?.47:.5),r}}
function draw(){ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w/2,h*.48,20,w/2,h*.48,Math.max(w,h)*.75);g.addColorStop(0,"#39205d");g.addColorStop(.48,"#1c102e");g.addColorStop(1,"#090512");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(105,238,224,.16)";ctx.lineWidth=1;for(let x=-h;x<w+h;x+=68){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-h*.35,h);ctx.stroke()}const {x,y,r}=layout(),step=Math.PI*2/7;ctx.save();ctx.translate(x,y);ctx.shadowBlur=34;ctx.shadowColor="#69eee0";ctx.beginPath();ctx.arc(0,0,r+15,0,Math.PI*2);ctx.strokeStyle="#69eee0";ctx.lineWidth=8;ctx.stroke();ctx.shadowBlur=0;for(let i=0;i<7;i++){const a0=angle+i*step-Math.PI/2-step/2,a1=a0+step;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a0,a1);ctx.closePath();ctx.fillStyle=CHARS[i].color;ctx.fill();ctx.strokeStyle="#21142f";ctx.lineWidth=4;ctx.stroke();const a=(a0+a1)/2,ix=Math.cos(a)*r*.62,iy=Math.sin(a)*r*.62,sz=r*.27;ctx.save();ctx.translate(ix,iy);ctx.rotate(a+Math.PI/2);ctx.beginPath();ctx.arc(0,0,sz*.58,0,Math.PI*2);ctx.clip();if(atlas.complete&&atlas.naturalWidth){const sw=atlas.naturalWidth/4,sh=atlas.naturalHeight/2;ctx.drawImage(atlas,(i%4)*sw,Math.floor(i/4)*sh,sw,sh,-sz*.58,-sz*.58,sz*1.16,sz*1.16)}ctx.restore()}ctx.beginPath();ctx.arc(0,0,r*.16,0,Math.PI*2);ctx.fillStyle="#1d102c";ctx.fill();ctx.strokeStyle="#ffd36e";ctx.lineWidth=6;ctx.stroke();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`900 ${Math.max(15,r*.075)}px system-ui`;ctx.fillText("GLITCH",0,0);ctx.restore();ctx.save();ctx.translate(x,y-r-26);ctx.shadowBlur=20;ctx.shadowColor="#ffd36e";ctx.fillStyle="#ffd36e";ctx.beginPath();ctx.moveTo(0,24);ctx.lineTo(-22,-10);ctx.lineTo(22,-10);ctx.closePath();ctx.fill();ctx.restore()}
let lastTick=-1;function spin(){if(spinning)return;requestTheme("play",!sound);spinning=true;spinBtn.disabled=true;statusEl.textContent="轉盤正在旋轉……";const target=Math.floor(Math.random()*7),step=Math.PI*2/7;from=angle;const desired=-(target*step)+Math.PI*2*6;to=from+desired-(from%(Math.PI*2));duration=4200+Math.random()*700;start=performance.now();lastTick=-1;requestAnimationFrame(frame)}
function frame(now){const p=Math.min((now-start)/duration,1),e=1-Math.pow(1-p,4);angle=from+(to-from)*e;const tick=Math.floor(angle/(Math.PI*2/28));if(tick!==lastTick){lastTick=tick;beep(190+(tick%7)*18,.025,.012,"square")}draw();if(p<1)requestAnimationFrame(frame);else finish()}
function finish(){spinning=false;angle=((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2);const step=Math.PI*2/7,index=(Math.round((-angle)/step)%7+7)%7,c=CHARS[index];data.spins++;if(!data.owned.includes(c.id))data.owned.push(c.id);try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}paintCount();statusEl.innerHTML=`指針選中了 <b>${c.name}</b>。`;reveal.innerHTML=`<div class="card"><div class="eyebrow">今日幸運角色</div><div class="big"><span class="avatar" style="${avatarStyle(index)}"></span></div><h2>${c.name}</h2><p>「${c.line}」</p><button>再轉一次</button></div>`;reveal.hidden=false;reveal.querySelector("button").onclick=()=>{reveal.hidden=true;spinBtn.disabled=false;statusEl.textContent="按下轉盤，看看下一次會遇見誰。"};[523,659,784].forEach((f,i)=>setTimeout(()=>beep(f,.18,.045),i*110))}
function paintCount(){count.textContent=data.owned.length}function openCollection(){collection.innerHTML=`<div class="card"><div class="head"><span>轉盤收藏（${data.owned.length}/7）</span><button>關閉</button></div>${CHARS.map((c,i)=>`<div class="row"><span class="mini"><span class="avatar" style="${avatarStyle(i)}"></span></span><div><b>${c.name}</b><br><small>${data.owned.includes(c.id)?"已經轉到":"還沒遇見"}</small></div></div>`).join("")}</div>`;collection.hidden=false;collection.querySelector("button").onclick=()=>collection.hidden=true}$("#collectionButton").onclick=openCollection;spinBtn.onclick=spin;canvas.onclick=spin;addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();spin()}});paintCount();draw();
